In [6]:
import pandas as pd

In [7]:
data = pd.read_csv('Train Dataset.csv')

In [8]:
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000
10,11,20,RL,70.0,11200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,129500
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,New,Partial,345000
12,13,20,RL,NaN,12968,Pave,NaN,IR2,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,144000
13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,New,Partial,279500
14,15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2008,WD,Normal,157000
15,16,45,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,7,2007,WD,Normal,132000
16,17,20,RL,NaN,11241,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,700,3,2010,WD,Normal,149000
17,18,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,Shed,500,10,2006,WD,Normal,90000
18,19,20,RL,66.0,13695,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,159000
19,20,20,RL,70.0,7560,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2009,COD,Abnorml,139000
20,21,60,RL,101.0,14215,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,New,Partial,325300
21,22,45,RM,57.0,7449,Pave,Grvl,Reg,Bnk,AllPub,...,0,NaN,GdPrv,NaN,0,6,2007,WD,Normal,139400
22,23,20,RL,75.0,9742,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,230000
23,24,120,RM,44.0,4224,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,129900
24,25,20,RL,NaN,8246,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2010,WD,Normal,154000
25,26,20,RL,110.0,14230,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,256300
26,27,20,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,134800
27,28,20,RL,98.0,11478,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,306000
28,29,20,RL,47.0,16321,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2006,WD,Normal,207500
29,30,30,RM,60.0,6324,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,1431,60,RL,60.0,21930,Pave,NaN,IR3,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,192140
1431,1432,120,RL,NaN,4928,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,143750
1432,1433,30,RL,60.0,10800,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,64500
1433,1434,60,RL,93.0,10261,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,186500
1434,1435,20,RL,80.0,17400,Pave,NaN,Reg,Low,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,160000
1435,1436,20,RL,80.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,7,2008,COD,Abnorml,174000
1436,1437,20,RL,60.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2007,WD,Normal,120500
1437,1438,20,RL,96.0,12444,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2008,New,Partial,394617
1438,1439,20,RM,90.0,7407,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,4,2010,WD,Normal,149700
1439,1440,60,RL,80.0,11584,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,197000
1440,1441,70,RL,79.0,11526,Pave,NaN,IR1,Bnk,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,191000
1441,1442,120,RM,NaN,4426,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,149300
1442,1443,60,FV,85.0,11003,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,310000
1443,1444,30,RL,NaN,8854,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,121000
1444,1445,20,RL,63.0,8500,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,179600
1445,1446,85,RL,70.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,129000
1446,1447,20,RL,NaN,26142,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,157900
1447,1448,60,RL,80.0,10000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,240000
1448,1449,50,RL,70.0,11767,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2007,WD,Normal,112000
1449,1450,180,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2006,WD,Abnorml,92000
1450,1451,90,RL,60.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2009,WD,Normal,136000
1451,1452,20,RL,78.0,9262,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,New,Partial,287090
1452,1453,180,RM,35.0,3675,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,145000
1453,1454,20,RL,90.0,17217,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Abnorml,84500
1454,1455,20,FV,62.0,7500,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,185000
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [9]:
data.head(3)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500

In [10]:
MSZoning_values=data['MSZoning']

In [11]:
MSZoning_values

0       RL
1       RL
2       RL
3       RL
4       RL
5       RL
6       RL
7       RL
8       RM
9       RL
10      RL
11      RL
12      RL
13      RL
14      RL
15      RM
16      RL
17      RL
18      RL
19      RL
20      RL
21      RM
22      RL
23      RM
24      RL
25      RL
26      RL
27      RL
28      RL
29      RM
        ..
1430    RL
1431    RL
1432    RL
1433    RL
1434    RL
1435    RL
1436    RL
1437    RL
1438    RM
1439    RL
1440    RL
1441    RM
1442    FV
1443    RL
1444    RL
1445    RL
1446    RL
1447    RL
1448    RL
1449    RM
1450    RL
1451    RL
1452    RM
1453    RL
1454    FV
1455    RL
1456    RL
1457    RL
1458    RL
1459    RL
Name: MSZoning, Length: 1460, dtype: object

In [12]:
type(MSZoning_values)

pandas.core.series.Series

In [13]:
MSZoning_values=set(MSZoning_values)         #extracting only the distinct values by using 'set' function

In [14]:
MSZoning_values

{'C (all)', 'FV', 'RH', 'RL', 'RM'}

In [15]:
MSZoning_dict={}         #creating an empty dictionary

In [16]:
count=1
for i in MSZoning_values:
  MSZoning_dict[i]=count
  count+=1

In [17]:
MSZoning_dict

{'RL': 1, 'RM': 2, 'C (all)': 3, 'RH': 4, 'FV': 5}

In [18]:
l=list(data['MSZoning'])

In [19]:
l

['RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'C (all)',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'RM',
 'RL',
 'RL',
 'RM',
 'RM',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RM',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'C (all)',
 'RL',
 'RL',
 'RL',
 'RL',
 'C (all)',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'FV',
 'RM',
 'RM',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RM',
 'RM',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'FV',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RL',
 'RM',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'RM',
 'RM',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RM',
 'RM',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RH',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RH',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'FV',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RM',
 'RM',
 'RL',
 'RM',
 'RL',
 'RM',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RM',
 'RM',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RM',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RM',
 'RL',
 'RL',
 'RL',
 'RM',
 'C (all)',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'FV',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'FV',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RH',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'FV',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'C (all)',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'RM',
 'RL',
 'RL',
 'RL',
 'RM',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RH',
 'RM',
 'RM',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'FV',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RH',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RH',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'FV',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'C (all)',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RM',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RH',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RM',
 'C (all)',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'FV',
 'RL',
 'RM',
 'RL',
 'RL',
 'FV',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RM',
 'RL',
 'RL',
 'RH',
 'RM',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RH',
 'FV',
 'RM',
 'C (all)',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RH',
 'RL',
 'RL',
 'RL',
 'RH',
 'RM',
 'RL',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'FV',
 'RL',
 'FV',
 'RL',
 'FV',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 'RL',
 'FV',
 'RL',
 'RM',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RL',
 'RM',
 'RL',
 ...]

In [20]:
for i in l:
  data['MSZoning']=MSZoning_dict[i]

In [21]:
data['MSZoning']

0       1
1       1
2       1
3       1
4       1
5       1
6       1
7       1
8       1
9       1
10      1
11      1
12      1
13      1
14      1
15      1
16      1
17      1
18      1
19      1
20      1
21      1
22      1
23      1
24      1
25      1
26      1
27      1
28      1
29      1
       ..
1430    1
1431    1
1432    1
1433    1
1434    1
1435    1
1436    1
1437    1
1438    1
1439    1
1440    1
1441    1
1442    1
1443    1
1444    1
1445    1
1446    1
1447    1
1448    1
1449    1
1450    1
1451    1
1452    1
1453    1
1454    1
1455    1
1456    1
1457    1
1458    1
1459    1
Name: MSZoning, Length: 1460, dtype: int64

In [22]:
Street_values=data['Street']

In [23]:
type(Street_values)

pandas.core.series.Series

In [24]:
Street_values=set(Street_values)

In [25]:
Street_values

{'Grvl', 'Pave'}

In [26]:
Street_dict={}

In [27]:
count=1
for i in Street_values:
  Street_dict[i]=count
  count+=1

In [28]:
Street_dict

{'Pave': 1, 'Grvl': 2}

In [29]:
a = list(data['Street'])

In [30]:
data['Street']=[Street_dict[i] for i in a]

In [31]:
Street_dict['Pave']

1

In [32]:
Street_dict['Grvl']

2

In [33]:
data['Street']

0       1
1       1
2       1
3       1
4       1
5       1
6       1
7       1
8       1
9       1
10      1
11      1
12      1
13      1
14      1
15      1
16      1
17      1
18      1
19      1
20      1
21      1
22      1
23      1
24      1
25      1
26      1
27      1
28      1
29      1
       ..
1430    1
1431    1
1432    1
1433    1
1434    1
1435    1
1436    1
1437    1
1438    1
1439    1
1440    1
1441    1
1442    1
1443    1
1444    1
1445    1
1446    1
1447    1
1448    1
1449    1
1450    1
1451    1
1452    1
1453    1
1454    1
1455    1
1456    1
1457    1
1458    1
1459    1
Name: Street, Length: 1460, dtype: int64

In [34]:
LotShape_values=data['LotShape']

In [35]:
type(LotShape_values)

pandas.core.series.Series

In [36]:
LotShape_values=set(LotShape_values)

In [37]:
LotShape_dict={}

In [38]:
count=1
for i in LotShape_values:
  LotShape_dict[i]=count
  count+=1

In [39]:
LotShape_dict

{'IR2': 1, 'IR1': 2, 'Reg': 3, 'IR3': 4}

In [40]:
l=list(data['LotShape'])

In [41]:
LandContour_values=data['LandContour']

In [42]:
type(LandContour_values)

pandas.core.series.Series

In [43]:
LandContour_values=set(LandContour_values)

In [44]:
LandContour_values

{'Bnk', 'HLS', 'Low', 'Lvl'}

In [45]:
LandContour_dict={}

In [46]:
count=1
for i in LandContour_values:
  LandContour_dict[i]=count
  count+=1

In [47]:
LandContour_dict

{'Lvl': 1, 'Bnk': 2, 'HLS': 3, 'Low': 4}

In [48]:
l=list(data['LandContour'])

In [49]:
data['LandContour']=[LandContour_dict[i] for i in l]

In [50]:
LandContour_dict['Lvl']

1

In [51]:
data['LandContour']

0       1
1       1
2       1
3       1
4       1
5       1
6       1
7       1
8       1
9       1
10      1
11      1
12      1
13      1
14      1
15      1
16      1
17      1
18      1
19      1
20      1
21      2
22      1
23      1
24      1
25      1
26      1
27      1
28      1
29      1
       ..
1430    1
1431    1
1432    1
1433    1
1434    4
1435    1
1436    1
1437    1
1438    1
1439    1
1440    2
1441    1
1442    1
1443    1
1444    1
1445    1
1446    1
1447    1
1448    1
1449    1
1450    1
1451    1
1452    1
1453    1
1454    1
1455    1
1456    1
1457    1
1458    1
1459    1
Name: LandContour, Length: 1460, dtype: int64

In [52]:
LotConfig_values=data['LotConfig']

In [53]:
LotConfig_values=set(LotConfig_values)

In [54]:
LotConfig_values

{'Corner', 'CulDSac', 'FR2', 'FR3', 'Inside'}

In [55]:
LotConfig_dict={}

In [56]:
count=1
for i in LotConfig_values:
  LotConfig_dict[i]=count
  count+=1

In [57]:
LotConfig_dict

{'FR3': 1, 'CulDSac': 2, 'FR2': 3, 'Inside': 4, 'Corner': 5}

In [58]:
l=list(data['LotConfig'])

In [59]:
data['LotConfig']=[LotConfig_dict[i] for i in l]

In [60]:
data['LotConfig']

0       4
1       3
2       4
3       5
4       3
5       4
6       4
7       5
8       4
9       5
10      4
11      4
12      4
13      4
14      5
15      5
16      2
17      4
18      4
19      4
20      5
21      4
22      4
23      4
24      4
25      5
26      5
27      4
28      2
29      4
       ..
1430    4
1431    4
1432    4
1433    4
1434    4
1435    4
1436    3
1437    3
1438    4
1439    4
1440    4
1441    4
1442    4
1443    4
1444    3
1445    4
1446    2
1447    4
1448    4
1449    4
1450    3
1451    4
1452    4
1453    4
1454    4
1455    4
1456    4
1457    4
1458    4
1459    4
Name: LotConfig, Length: 1460, dtype: int64

In [61]:
LandSlope_values=data['LandSlope']

In [62]:
LandSlope_values=set(LandSlope_values)

In [63]:
LandSlope_values

{'Gtl', 'Mod', 'Sev'}

In [64]:
LandSlope_dict={}

In [65]:
count=1
for i in LandSlope_values:
  LandSlope_dict[i]=count
  count+=1

In [66]:
LandSlope_dict

{'Gtl': 1, 'Sev': 2, 'Mod': 3}

In [67]:
l=list(data['LandSlope'])

In [68]:
data['LandSlope']=[LandSlope_dict[i] for i in l]

In [69]:
data['LandSlope']

0       1
1       1
2       1
3       1
4       1
5       1
6       1
7       1
8       1
9       1
10      1
11      1
12      1
13      1
14      1
15      1
16      1
17      1
18      1
19      1
20      1
21      1
22      1
23      1
24      1
25      1
26      1
27      1
28      1
29      1
       ..
1430    1
1431    1
1432    1
1433    1
1434    3
1435    1
1436    1
1437    1
1438    1
1439    1
1440    3
1441    1
1442    1
1443    1
1444    1
1445    1
1446    1
1447    1
1448    1
1449    1
1450    1
1451    1
1452    1
1453    1
1454    1
1455    1
1456    1
1457    1
1458    1
1459    1
Name: LandSlope, Length: 1460, dtype: int64

In [70]:
N_values=data['Neighborhood']

In [71]:
N_values=set(N_values)

In [72]:
N_values

{'Blmngtn',
 'Blueste',
 'BrDale',
 'BrkSide',
 'ClearCr',
 'CollgCr',
 'Crawfor',
 'Edwards',
 'Gilbert',
 'IDOTRR',
 'MeadowV',
 'Mitchel',
 'NAmes',
 'NPkVill',
 'NWAmes',
 'NoRidge',
 'NridgHt',
 'OldTown',
 'SWISU',
 'Sawyer',
 'SawyerW',
 'Somerst',
 'StoneBr',
 'Timber',
 'Veenker'}

In [73]:
N_dict={}

In [74]:
count=1
for i in N_values:
  N_dict[i]=count
  count+=1

In [75]:
N_dict

{'Mitchel': 1,
 'NridgHt': 2,
 'NWAmes': 3,
 'SWISU': 4,
 'IDOTRR': 5,
 'NoRidge': 6,
 'Crawfor': 7,
 'CollgCr': 8,
 'BrkSide': 9,
 'NPkVill': 10,
 'Blueste': 11,
 'MeadowV': 12,
 'Somerst': 13,
 'OldTown': 14,
 'Timber': 15,
 'StoneBr': 16,
 'Gilbert': 17,
 'Veenker': 18,
 'NAmes': 19,
 'BrDale': 20,
 'Edwards': 21,
 'Blmngtn': 22,
 'ClearCr': 23,
 'SawyerW': 24,
 'Sawyer': 25}

In [76]:
l=list(data['Neighborhood'])

In [77]:
data['Neighborhood']=[N_dict[i] for i in l]

In [78]:
data['Neighborhood']

0        8
1       18
2        8
3        7
4        6
5        1
6       13
7        3
8       14
9        9
10      25
11       2
12      25
13       8
14      19
15       9
16      19
17      25
18      24
19      19
20       2
21       5
22       8
23      12
24      25
25       2
26      19
27       2
28      19
29       9
        ..
1430    17
1431    10
1432    14
1433    17
1434     1
1435    19
1436    19
1437     2
1438    14
1439     3
1440     7
1441     8
1442    13
1443     9
1444     8
1445    25
1446     1
1447     8
1448    21
1449    12
1450    19
1451    13
1452    21
1453     1
1454    13
1455    17
1456     3
1457     7
1458    19
1459    21
Name: Neighborhood, Length: 1460, dtype: int64

In [79]:
Condition1_values=data['Condition1']
Condition1_values=set(Condition1_values)
Condition1_dict={}


count=1
for i in Condition1_values:
  Condition1_dict[i]=count
  count+=1
    
    
l=list(data['Condition1'])
data['Condition1']=[Condition1_dict[i] for i in l]

In [80]:
data['Condition1']

0       2
1       3
2       2
3       2
4       2
5       2
6       2
7       4
8       6
9       6
10      2
11      2
12      2
13      2
14      2
15      2
16      2
17      2
18      7
19      2
20      2
21      2
22      2
23      2
24      2
25      2
26      2
27      2
28      2
29      3
       ..
1430    5
1431    2
1432    2
1433    2
1434    2
1435    2
1436    2
1437    2
1438    6
1439    2
1440    2
1441    2
1442    2
1443    2
1444    2
1445    2
1446    2
1447    2
1448    2
1449    2
1450    2
1451    2
1452    2
1453    2
1454    2
1455    2
1456    2
1457    2
1458    2
1459    2
Name: Condition1, Length: 1460, dtype: int64

In [81]:
Condition2_values=data['Condition2']
Condition2_values=set(Condition2_values)
Condition2_dict={}


count=1
for i in Condition2_values:
  Condition2_dict[i]=count
  count+=1
    
    
l=list(data['Condition2'])
data['Condition2']=[Condition2_dict[i] for i in l]

In [82]:
data['Condition2']

0       2
1       2
2       2
3       2
4       2
5       2
6       2
7       2
8       2
9       6
10      2
11      2
12      2
13      2
14      2
15      2
16      2
17      2
18      2
19      2
20      2
21      2
22      2
23      2
24      2
25      2
26      2
27      2
28      2
29      1
       ..
1430    2
1431    2
1432    2
1433    2
1434    2
1435    2
1436    2
1437    2
1438    2
1439    2
1440    2
1441    2
1442    2
1443    2
1444    2
1445    2
1446    2
1447    2
1448    2
1449    2
1450    2
1451    2
1452    2
1453    2
1454    2
1455    2
1456    2
1457    2
1458    2
1459    2
Name: Condition2, Length: 1460, dtype: int64

In [83]:
BldgType_values=data['BldgType']
BldgType_values=set(BldgType_values)
BldgType_dict={}


count=1
for i in BldgType_values:
  BldgType_dict[i]=count
  count+=1
    
    
l=list(data['BldgType'])
data['BldgType']=[BldgType_dict[i] for i in l]

In [84]:
data['BldgType']

0       2
1       2
2       2
3       2
4       2
5       2
6       2
7       2
8       2
9       1
10      2
11      2
12      2
13      2
14      2
15      2
16      2
17      5
18      2
19      2
20      2
21      2
22      2
23      4
24      2
25      2
26      2
27      2
28      2
29      2
       ..
1430    2
1431    4
1432    2
1433    2
1434    2
1435    2
1436    2
1437    2
1438    2
1439    2
1440    2
1441    4
1442    2
1443    2
1444    2
1445    2
1446    2
1447    2
1448    2
1449    3
1450    5
1451    2
1452    4
1453    2
1454    2
1455    2
1456    2
1457    2
1458    2
1459    2
Name: BldgType, Length: 1460, dtype: int64

In [85]:
HouseStyle_values=data['HouseStyle']
HouseStyle_values=set(HouseStyle_values)
HouseStyle_dict={}


count=1
for i in HouseStyle_values:
  HouseStyle_dict[i]=count
  count+=1
    
    
l=list(data['HouseStyle'])
data['HouseStyle']=[HouseStyle_dict[i] for i in l]

In [86]:
data['HouseStyle']

0       5
1       2
2       5
3       5
4       5
5       6
6       2
7       5
8       6
9       3
10      2
11      5
12      2
13      2
14      2
15      3
16      2
17      2
18      2
19      2
20      5
21      3
22      2
23      2
24      2
25      2
26      2
27      2
28      2
29      2
       ..
1430    5
1431    2
1432    2
1433    5
1434    2
1435    2
1436    2
1437    2
1438    2
1439    7
1440    1
1441    2
1442    5
1443    3
1444    2
1445    4
1446    2
1447    5
1448    5
1449    4
1450    5
1451    2
1452    7
1453    2
1454    2
1455    5
1456    2
1457    5
1458    2
1459    2
Name: HouseStyle, Length: 1460, dtype: int64

In [87]:
OverallQual_values=data['OverallQual']
OverallQual_values=set(OverallQual_values)
OverallQual_dict={}


count=1
for i in OverallQual_values:
  OverallQual_dict[i]=count
  count+=1
    
    
l=list(data['OverallQual'])
data['OverallQual']=[OverallQual_dict[i] for i in l]

In [88]:
data['OverallQual']

0        7
1        6
2        7
3        7
4        8
5        5
6        8
7        7
8        7
9        5
10       5
11       9
12       5
13       7
14       6
15       7
16       6
17       4
18       5
19       5
20       8
21       7
22       8
23       5
24       5
25       8
26       5
27       8
28       5
29       4
        ..
1430     5
1431     6
1432     4
1433     6
1434     5
1435     6
1436     4
1437     8
1438     6
1439     7
1440     6
1441     6
1442    10
1443     6
1444     7
1445     6
1446     5
1447     8
1448     4
1449     5
1450     5
1451     8
1452     5
1453     5
1454     7
1455     6
1456     6
1457     7
1458     5
1459     5
Name: OverallQual, Length: 1460, dtype: int64

In [89]:
RoofStyle_values=data['RoofStyle']
RoofStyle_values=set(RoofStyle_values)
RoofStyle_dict={}


count=1
for i in RoofStyle_values:
  RoofStyle_dict[i]=count
  count+=1
    
    
l=list(data['RoofStyle'])
data['RoofStyle']=[RoofStyle_dict[i] for i in l]

In [90]:
data['RoofStyle']

0       6
1       6
2       6
3       6
4       6
5       6
6       6
7       6
8       6
9       6
10      5
11      5
12      5
13      6
14      5
15      6
16      6
17      6
18      6
19      5
20      6
21      6
22      5
23      6
24      6
25      6
26      6
27      6
28      6
29      6
       ..
1430    6
1431    6
1432    6
1433    6
1434    6
1435    6
1436    6
1437    5
1438    6
1439    5
1440    6
1441    6
1442    6
1443    6
1444    6
1445    6
1446    6
1447    6
1448    6
1449    6
1450    6
1451    6
1452    6
1453    6
1454    6
1455    6
1456    6
1457    6
1458    5
1459    6
Name: RoofStyle, Length: 1460, dtype: int64

In [91]:
RoofMatl_values=data['RoofMatl']
RoofMatl_values=set(RoofMatl_values)
RoofMatl_dict={}


count=1
for i in RoofMatl_values:
  RoofMatl_dict[i]=count
  count+=1
    
    
l=list(data['RoofMatl'])
data['RoofMatl']=[RoofMatl_dict[i] for i in l]

In [92]:
data['RoofMatl']

0       5
1       5
2       5
3       5
4       5
5       5
6       5
7       5
8       5
9       5
10      5
11      5
12      5
13      5
14      5
15      5
16      5
17      5
18      5
19      5
20      5
21      5
22      5
23      5
24      5
25      5
26      5
27      5
28      5
29      5
       ..
1430    5
1431    5
1432    5
1433    5
1434    5
1435    5
1436    5
1437    5
1438    5
1439    5
1440    5
1441    5
1442    5
1443    5
1444    5
1445    5
1446    5
1447    5
1448    5
1449    5
1450    5
1451    5
1452    5
1453    5
1454    5
1455    5
1456    5
1457    5
1458    5
1459    5
Name: RoofMatl, Length: 1460, dtype: int64

In [93]:
Exterior1st_values=data['Exterior1st']
Exterior1st_values=set(Exterior1st_values)
Exterior1st_dict={}


count=1
for i in Exterior1st_values:
  Exterior1st_dict[i]=count
  count+=1
    
    
l=list(data['Exterior1st'])
data['Exterior1st']=[Exterior1st_dict[i] for i in l]

In [94]:
data['Exterior1st']

0        6
1        4
2        6
3        2
4        6
5        6
6        6
7        9
8       12
9        4
10       9
11      14
12       9
13       6
14       4
15       2
16       2
17       4
18       6
19      12
20       6
21       2
22       6
23       1
24      15
25       6
26       2
27       6
28       4
29       4
        ..
1430     6
1431    15
1432     2
1433     6
1434    12
1435     2
1436     9
1437     6
1438     4
1439     9
1440     4
1441     6
1442     6
1443     2
1444     6
1445     6
1446     9
1447     6
1448     4
1449     1
1450     6
1451     1
1452     6
1453     6
1454     6
1455     6
1456    15
1457     1
1458     4
1459     9
Name: Exterior1st, Length: 1460, dtype: int64

In [95]:
Exterior2nd_values=data['Exterior2nd']
Exterior2nd_values=set(Exterior2nd_values)
Exterior2nd_dict={}


count=1
for i in Exterior2nd_values:
  Exterior2nd_dict[i]=count
  count+=1
    
    
l=list(data['Exterior2nd'])
data['Exterior2nd']=[Exterior2nd_dict[i] for i in l]

In [96]:
data['Exterior2nd']

0        7
1        5
2        7
3        9
4        7
5        7
6        7
7       10
8        9
9        5
10      10
11       9
12      16
13       7
14       5
15       3
16       3
17       5
18       7
19      16
20       7
21       3
22       7
23       2
24      16
25       7
26       3
27       7
28       5
29       5
        ..
1430     7
1431    16
1432     3
1433     7
1434    14
1435     3
1436    10
1437     7
1438     5
1439    10
1440     5
1441     7
1442     7
1443     3
1444     7
1445     7
1446    10
1447     7
1448    10
1449     2
1450     7
1451     2
1452     7
1453     7
1454     7
1455     7
1456    16
1457     2
1458     5
1459    10
Name: Exterior2nd, Length: 1460, dtype: int64

In [97]:
MasVnrType_values=data['MasVnrType']
MasVnrType_values=set(MasVnrType_values)

In [98]:
MasVnrType_values

{'BrkCmn', 'BrkFace', 'None', 'Stone', nan}

In [99]:
MasVnrType_dict={}
MasVnrType_dict['None'] = 0
MasVnrType_dict['nan'] = 0
MasVnrType_dict['BrkFace'] = 1
MasVnrType_dict['Stone'] = 2
MasVnrType_dict['BrkCmn'] = 3

In [100]:
MasVnrType_dict

{'None': 0, 'nan': 0, 'BrkFace': 1, 'Stone': 2, 'BrkCmn': 3}

In [101]:
l=list(data['MasVnrType'])
data['MasVnrType']=[MasVnrType_dict[i] for i in l]

KeyError: nan

In [102]:
ExterQual_values=data['ExterQual']
ExterQual_values=set(ExterQual_values)
ExterQual_dict={}


count=1
for i in ExterQual_values:
  ExterQual_dict[i]=count
  count+=1
    
    
l=list(data['ExterQual'])
data['ExterQual']=[ExterQual_dict[i] for i in l]

In [103]:
data['ExterQual']

0       4
1       1
2       4
3       1
4       4
5       1
6       4
7       1
8       1
9       1
10      1
11      2
12      1
13      4
14      1
15      1
16      1
17      1
18      1
19      1
20      4
21      1
22      4
23      1
24      1
25      4
26      1
27      4
28      1
29      1
       ..
1430    4
1431    1
1432    1
1433    1
1434    1
1435    4
1436    1
1437    2
1438    1
1439    1
1440    1
1441    4
1442    2
1443    1
1444    4
1445    1
1446    1
1447    4
1448    1
1449    1
1450    1
1451    4
1452    1
1453    1
1454    4
1455    1
1456    1
1457    2
1458    1
1459    4
Name: ExterQual, Length: 1460, dtype: int64

In [104]:
ExterCond_values=data['ExterCond']
ExterCond_values=set(ExterCond_values)
ExterCond_dict={}


count=1
for i in ExterCond_values:
  ExterCond_dict[i]=count
  count+=1
    
    
l=list(data['ExterCond'])
data['ExterCond']=[ExterCond_dict[i] for i in l]

In [105]:
data['ExterCond']

0       3
1       3
2       3
3       3
4       3
5       3
6       3
7       3
8       3
9       3
10      3
11      3
12      3
13      3
14      3
15      3
16      3
17      3
18      3
19      3
20      3
21      3
22      3
23      3
24      4
25      3
26      3
27      3
28      3
29      3
       ..
1430    3
1431    3
1432    3
1433    3
1434    3
1435    4
1436    3
1437    3
1438    3
1439    3
1440    3
1441    3
1442    3
1443    3
1444    3
1445    3
1446    3
1447    3
1448    3
1449    3
1450    3
1451    3
1452    3
1453    3
1454    3
1455    3
1456    3
1457    4
1458    3
1459    3
Name: ExterCond, Length: 1460, dtype: int64

In [106]:
Foundation_values=data['Foundation']
Foundation_values=set(Foundation_values)
Foundation_dict={}


count=1
for i in Foundation_values:
  Foundation_dict[i]=count
  count+=1
    
    
l=list(data['Foundation'])
data['Foundation']=[Foundation_dict[i] for i in l]

In [107]:
data['Foundation']

0       4
1       1
2       4
3       3
4       4
5       5
6       4
7       1
8       3
9       3
10      1
11      4
12      1
13      4
14      1
15      3
16      1
17      2
18      4
19      1
20      4
21      4
22      4
23      4
24      1
25      4
26      1
27      4
28      1
29      3
       ..
1430    4
1431    1
1432    3
1433    4
1434    1
1435    1
1436    4
1437    4
1438    1
1439    1
1440    3
1441    4
1442    4
1443    3
1444    4
1445    1
1446    1
1447    4
1448    1
1449    1
1450    1
1451    4
1452    4
1453    4
1454    4
1455    4
1456    1
1457    6
1458    1
1459    1
Name: Foundation, Length: 1460, dtype: int64

In [108]:
BsmtQual_values=data['BsmtQual']
BsmtQual_values=set(BsmtQual_values)
BsmtQual_dict={}


count=1
for i in BsmtQual_values:
  BsmtQual_dict[i]=count
  count+=1
    
    
l=list(data['BsmtQual'])
data['BsmtQual']=[BsmtQual_dict[i] for i in l]

In [109]:
data['BsmtQual']

0       4
1       4
2       4
3       3
4       4
5       4
6       2
7       4
8       3
9       3
10      3
11      2
12      3
13      4
14      3
15      3
16      3
17      1
18      3
19      3
20      2
21      3
22      4
23      4
24      3
25      4
26      3
27      2
28      3
29      3
       ..
1430    4
1431    4
1432    3
1433    4
1434    3
1435    3
1436    3
1437    2
1438    3
1439    3
1440    2
1441    4
1442    2
1443    3
1444    4
1445    3
1446    3
1447    4
1448    5
1449    4
1450    4
1451    4
1452    4
1453    4
1454    4
1455    4
1456    4
1457    3
1458    3
1459    3
Name: BsmtQual, Length: 1460, dtype: int64

In [110]:
BsmtCond_values=data['BsmtCond']
BsmtCond_values=set(BsmtCond_values)
BsmtCond_dict={}


count=1
for i in BsmtCond_values:
  BsmtCond_dict[i]=count
  count+=1
    
    
l=list(data['BsmtCond'])
data['BsmtCond']=[BsmtCond_dict[i] for i in l]

In [111]:
data['BsmtCond']

0       3
1       3
2       3
3       4
4       3
5       3
6       3
7       3
8       3
9       3
10      3
11      3
12      3
13      3
14      3
15      3
16      3
17      1
18      3
19      3
20      3
21      3
22      3
23      3
24      3
25      3
26      3
27      3
28      3
29      3
       ..
1430    4
1431    3
1432    3
1433    3
1434    3
1435    3
1436    3
1437    3
1438    3
1439    3
1440    3
1441    3
1442    3
1443    3
1444    3
1445    3
1446    3
1447    3
1448    3
1449    3
1450    3
1451    3
1452    3
1453    3
1454    3
1455    3
1456    3
1457    4
1458    3
1459    3
Name: BsmtCond, Length: 1460, dtype: int64

In [112]:
BsmtExposure_values=data['BsmtExposure']
BsmtExposure_values=set(BsmtExposure_values)

In [113]:
BsmtExposure_values

{'Av', 'Gd', 'Mn', 'No', nan}

In [114]:
BsmtExposure_dict={}
BsmtExposure_dict['No'] = 0
BsmtExposure_dict['nan'] = 0
BsmtExposure_dict['Av'] = 1
BsmtExposure_dict['Gd'] = 2
BsmtExposure_dict['Mn'] = 3

In [115]:
BsmtExposure_dict

{'No': 0, 'nan': 0, 'Av': 1, 'Gd': 2, 'Mn': 3}

In [116]:
l=list(data['BsmtExposure'])
data['BsmtExposure']=[BsmtExposure_dict[i] for i in l]

KeyError: nan

In [117]:
BsmtFinType1_values=data['BsmtFinType1']
BsmtFinType1_values=set(BsmtFinType1_values)
BsmtFinType1_dict={}


count=1
for i in BsmtFinType1_values:
  BsmtFinType1_dict[i]=count
  count+=1
    
    
l=list(data['BsmtFinType1'])
data['BsmtFinType1']=[BsmtFinType1_dict[i] for i in l]

In [118]:
data['BsmtFinType1']

0       6
1       2
2       6
3       2
4       6
5       6
6       6
7       2
8       4
9       6
10      7
11      6
12      2
13      4
14      3
15      4
16      2
17      1
18      6
19      5
20      4
21      4
22      4
23      6
24      7
25      4
26      3
27      6
28      3
29      4
       ..
1430    4
1431    5
1432    4
1433    4
1434    2
1435    4
1436    2
1437    6
1438    6
1439    6
1440    4
1441    6
1442    6
1443    4
1444    4
1445    5
1446    7
1447    6
1448    4
1449    6
1450    4
1451    4
1452    6
1453    4
1454    6
1455    4
1456    2
1457    6
1458    6
1459    3
Name: BsmtFinType1, Length: 1460, dtype: int64

In [119]:
BsmtFinType2_values=data['BsmtFinType2']
BsmtFinType2_values=set(BsmtFinType2_values)

In [120]:
BsmtFinType2_values

{'ALQ', 'BLQ', 'GLQ', 'LwQ', 'Rec', 'Unf', nan}

In [124]:
BsmtFinType2_dict={}
BsmtFinType2_dict['nan'] = 0
BsmtFinType2_dict['ALQ'] = 1
BsmtFinType2_dict['BLQ'] = 2
BsmtFinType2_dict['GLQ'] = 3
BsmtFinType2_dict['LwQ'] = 4
BsmtFinType2_dict['Rec'] = 5
BsmtFinType2_dict['Unf'] = 6

In [125]:
BsmtFinType2_dict

{'nan': 0, 'ALQ': 1, 'BLQ': 2, 'GLQ': 3, 'LwQ': 4, 'Rec': 5, 'Unf': 6}

In [139]:
l=list(data['BsmtFinType2'])
i = 0
for i in l:
    data['BsmtFinType2']=BsmtFinType2_dict[i]

KeyError: nan

In [148]:
Heating_values=data['Heating']
Heating_values=set(Heating_values)
Heating_dict={}


count=1
for i in Heating_values:
  Heating_dict[i]=count
  count+=1
    
    
l=list(data['Heating'])
data['Heating']=[Heating_dict[i] for i in l]

In [149]:
data['Heating']

0       6
1       6
2       6
3       6
4       6
5       6
6       6
7       6
8       6
9       6
10      6
11      6
12      6
13      6
14      6
15      6
16      6
17      6
18      6
19      6
20      6
21      6
22      6
23      6
24      6
25      6
26      6
27      6
28      6
29      6
       ..
1430    6
1431    6
1432    6
1433    6
1434    6
1435    6
1436    6
1437    6
1438    6
1439    6
1440    6
1441    6
1442    6
1443    4
1444    6
1445    6
1446    6
1447    6
1448    6
1449    6
1450    6
1451    6
1452    6
1453    6
1454    6
1455    6
1456    6
1457    6
1458    6
1459    6
Name: Heating, Length: 1460, dtype: int64

In [150]:
HeatingQC_values=data['HeatingQC']
HeatingQC_values=set(HeatingQC_values)
HeatingQC_dict={}


count=1
for i in HeatingQC_values:
  HeatingQC_dict[i]=count
  count+=1
    
    
l=list(data['HeatingQC'])
data['HeatingQC']=[HeatingQC_dict[i] for i in l]

In [151]:
data['HeatingQC']

0       1
1       1
2       1
3       4
4       1
5       1
6       1
7       1
8       4
9       1
10      1
11      1
12      3
13      1
14      3
15      1
16      1
17      3
18      1
19      3
20      1
21      1
22      1
23      3
24      1
25      1
26      3
27      1
28      3
29      5
       ..
1430    1
1431    3
1432    3
1433    1
1434    5
1435    3
1436    3
1437    1
1438    3
1439    3
1440    5
1441    1
1442    1
1443    5
1444    1
1445    4
1446    3
1447    1
1448    4
1449    1
1450    3
1451    1
1452    4
1453    1
1454    1
1455    1
1456    3
1457    1
1458    4
1459    4
Name: HeatingQC, Length: 1460, dtype: int64

In [152]:
CentralAir_values=data['CentralAir']
CentralAir_values=set(CentralAir_values)

In [153]:
CentralAir_values

{'N', 'Y'}

In [154]:
CentralAir_dict={}


count=1
for i in CentralAir_values:
  CentralAir_dict[i]=count
  count+=1
    
    
l=list(data['CentralAir'])
data['CentralAir']=[CentralAir_dict[i] for i in l]

In [155]:
data['CentralAir']

0       2
1       2
2       2
3       2
4       2
5       2
6       2
7       2
8       2
9       2
10      2
11      2
12      2
13      2
14      2
15      2
16      2
17      2
18      2
19      2
20      2
21      2
22      2
23      2
24      2
25      2
26      2
27      2
28      2
29      1
       ..
1430    2
1431    2
1432    2
1433    2
1434    2
1435    2
1436    2
1437    2
1438    2
1439    2
1440    2
1441    2
1442    2
1443    1
1444    2
1445    2
1446    2
1447    2
1448    1
1449    2
1450    2
1451    2
1452    2
1453    2
1454    2
1455    2
1456    2
1457    2
1458    2
1459    2
Name: CentralAir, Length: 1460, dtype: int64

In [157]:
Electrical_values=data['Electrical']
Electrical_values=set(Electrical_values)
Electrical_dict={}


count=1
for i in Electrical_values:
  Electrical_dict[i]=count
  count+=1
    
    
l=list(data['Electrical'])
data['Electrical']=[Electrical_dict[i] for i in l]

In [158]:
data['Electrical']

0       5
1       5
2       5
3       5
4       5
5       5
6       5
7       5
8       6
9       5
10      5
11      5
12      5
13      5
14      5
15      2
16      5
17      5
18      5
19      5
20      5
21      6
22      5
23      5
24      5
25      5
26      5
27      5
28      5
29      5
       ..
1430    5
1431    5
1432    5
1433    5
1434    5
1435    5
1436    5
1437    5
1438    2
1439    5
1440    5
1441    5
1442    5
1443    6
1444    5
1445    5
1446    5
1447    5
1448    5
1449    5
1450    5
1451    5
1452    5
1453    5
1454    5
1455    5
1456    5
1457    5
1458    2
1459    5
Name: Electrical, Length: 1460, dtype: int64

In [159]:
KitchenQual_values=data['KitchenQual']
KitchenQual_values=set(KitchenQual_values)
KitchenQual_dict={}


count=1
for i in KitchenQual_values:
  KitchenQual_dict[i]=count
  count+=1
    
    
l=list(data['KitchenQual'])
data['KitchenQual']=[KitchenQual_dict[i] for i in l]

In [160]:
data['KitchenQual']

0       4
1       1
2       4
3       4
4       4
5       1
6       4
7       1
8       1
9       1
10      1
11      2
12      1
13      4
14      1
15      1
16      1
17      1
18      4
19      1
20      4
21      4
22      4
23      1
24      4
25      4
26      4
27      4
28      1
29      3
       ..
1430    1
1431    1
1432    1
1433    1
1434    1
1435    4
1436    1
1437    2
1438    1
1439    1
1440    1
1441    4
1442    2
1443    3
1444    4
1445    1
1446    1
1447    4
1448    1
1449    2
1450    1
1451    2
1452    1
1453    1
1454    4
1455    1
1456    1
1457    4
1458    4
1459    1
Name: KitchenQual, Length: 1460, dtype: int64

In [161]:
Functional_values=data['Functional']
Functional_values=set(Functional_values)

In [162]:
Functional_values

{'Maj1', 'Maj2', 'Min1', 'Min2', 'Mod', 'Sev', 'Typ'}

In [163]:
Functional_dict={}


count=1
for i in Functional_values:
  Functional_dict[i]=count
  count+=1
    
    
l=list(data['Functional'])
data['Functional']=[Functional_dict[i] for i in l]

In [164]:
data['Functional']

0       4
1       4
2       4
3       4
4       4
5       4
6       4
7       4
8       1
9       4
10      4
11      4
12      4
13      4
14      4
15      4
16      4
17      4
18      4
19      1
20      4
21      4
22      4
23      4
24      4
25      4
26      4
27      4
28      4
29      4
       ..
1430    4
1431    4
1432    4
1433    4
1434    4
1435    4
1436    4
1437    4
1438    4
1439    4
1440    1
1441    4
1442    4
1443    4
1444    4
1445    4
1446    4
1447    4
1448    3
1449    4
1450    4
1451    4
1452    4
1453    4
1454    4
1455    4
1456    1
1457    4
1458    4
1459    4
Name: Functional, Length: 1460, dtype: int64

In [165]:
FireplaceQu_values=data['FireplaceQu']
FireplaceQu_values=set(FireplaceQu_values)

In [166]:
FireplaceQu_values

{'Ex', 'Fa', 'Gd', 'Po', 'TA', nan}

In [167]:
GarageType_values=data['GarageType']
GarageType_values=set(GarageType_values)

In [168]:
GarageType_values

{'2Types', 'Attchd', 'Basment', 'BuiltIn', 'CarPort', 'Detchd', nan}

In [169]:
GarageFinish_values=data['GarageFinish']
GarageFinish_values=set(GarageFinish_values)

In [170]:
GarageFinish_values

{'Fin', 'RFn', 'Unf', nan}

In [171]:
GarageQual_values=data['GarageQual']
GarageQual_values=set(GarageQual_values)

In [172]:
GarageQual_values

{'Ex', 'Fa', 'Gd', 'Po', 'TA', nan}

In [173]:
GarageCond_values=data['GarageCond']
GarageCond_values=set(GarageCond_values)

In [174]:
GarageCond_values

{'Ex', 'Fa', 'Gd', 'Po', 'TA', nan}

In [175]:
PavedDrive_values=data['PavedDrive']
PavedDrive_values=set(PavedDrive_values)

In [176]:
PavedDrive_values

{'N', 'P', 'Y'}

In [177]:
PavedDrive_dict={}
PavedDrive_dict['N'] = -1
PavedDrive_dict['P'] = 2
PavedDrive_dict['Y'] = 1

In [178]:
PavedDrive_dict

{'N': -1, 'P': 2, 'Y': 1}

In [179]:
l=list(data['PavedDrive'])
data['PavedDrive']=[PavedDrive_dict[i] for i in l]

In [180]:
data['PavedDrive']

0       1
1       1
2       1
3       1
4       1
5       1
6       1
7       1
8       1
9       1
10      1
11      1
12      1
13      1
14      1
15      1
16      1
17      1
18      1
19      1
20      1
21     -1
22      1
23      1
24      1
25      1
26      1
27      1
28      1
29      1
       ..
1430    1
1431    1
1432    1
1433    1
1434    2
1435    1
1436    1
1437    1
1438    1
1439    1
1440    1
1441    1
1442    1
1443    2
1444    1
1445    1
1446    2
1447    1
1448    1
1449    1
1450    1
1451    1
1452    1
1453    1
1454    1
1455    1
1456    1
1457    1
1458    1
1459    1
Name: PavedDrive, Length: 1460, dtype: int64

In [181]:
PoolQC_values=data['PoolQC']
PoolQC_values=set(PoolQC_values)

In [182]:
PoolQC_values

{'Ex', 'Fa', 'Gd', nan}

In [183]:
SaleType_values=data['SaleType']
SaleType_values=set(SaleType_values)

In [184]:
SaleType_values

{'COD', 'CWD', 'Con', 'ConLD', 'ConLI', 'ConLw', 'New', 'Oth', 'WD'}

In [185]:
SaleType_dict={}


count=1
for i in SaleType_values:
  SaleType_dict[i]=count
  count+=1
    
    
l=list(data['SaleType'])
data['SaleType']=[SaleType_dict[i] for i in l]

In [186]:
data['SaleType']

0       8
1       8
2       8
3       8
4       8
5       8
6       8
7       8
8       8
9       8
10      8
11      5
12      8
13      5
14      8
15      8
16      8
17      8
18      8
19      1
20      5
21      8
22      8
23      8
24      8
25      8
26      8
27      8
28      8
29      8
       ..
1430    8
1431    8
1432    8
1433    8
1434    8
1435    1
1436    8
1437    5
1438    8
1439    8
1440    8
1441    8
1442    8
1443    8
1444    8
1445    8
1446    8
1447    8
1448    8
1449    8
1450    8
1451    5
1452    8
1453    8
1454    8
1455    8
1456    8
1457    8
1458    8
1459    8
Name: SaleType, Length: 1460, dtype: int64

In [187]:
SaleCondition_values=data['SaleCondition']
SaleCondition_values=set(SaleCondition_values)

In [188]:
SaleCondition_values

{'Abnorml', 'AdjLand', 'Alloca', 'Family', 'Normal', 'Partial'}

In [189]:
SaleCondition_dict={}


count=1
for i in SaleCondition_values:
  SaleCondition_dict[i]=count
  count+=1
    
    
l=list(data['SaleCondition'])
data['SaleCondition']=[SaleCondition_dict[i] for i in l]

In [191]:
data['SaleCondition']

0       4
1       4
2       4
3       1
4       4
5       4
6       4
7       4
8       1
9       4
10      4
11      3
12      4
13      3
14      4
15      4
16      4
17      4
18      4
19      1
20      3
21      4
22      4
23      4
24      4
25      4
26      4
27      4
28      4
29      4
       ..
1430    4
1431    4
1432    4
1433    4
1434    4
1435    1
1436    4
1437    3
1438    4
1439    4
1440    4
1441    4
1442    4
1443    4
1444    4
1445    4
1446    4
1447    4
1448    4
1449    1
1450    4
1451    3
1452    4
1453    1
1454    4
1455    4
1456    4
1457    4
1458    4
1459    4
Name: SaleCondition, Length: 1460, dtype: int64

In [192]:
correlation=data.corr()[['SalePrice']]

In [193]:
correlation.sort_values(by = 'SalePrice',ascending = False)

               SalePrice
SalePrice       1.000000
OverallQual     0.790982
GrLivArea       0.708624
GarageCars      0.640409
GarageArea      0.623431
TotalBsmtSF     0.613581
1stFlrSF        0.605852
FullBath        0.560664
TotRmsAbvGrd    0.533723
YearBuilt       0.522897
YearRemodAdd    0.507101
ExterQual       0.500579
GarageYrBlt     0.486362
MasVnrArea      0.477493
Fireplaces      0.466929
Foundation      0.418428
BsmtFinSF1      0.386420
KitchenQual     0.385820
LotFrontage     0.351799
WoodDeckSF      0.324413
2ndFlrSF        0.319334
OpenPorchSF     0.315856
HalfBath        0.284108
BsmtFinType1    0.265912
LotArea         0.263843
CentralAir      0.251328
BsmtFullBath    0.227122
BsmtUnfSF       0.214479
PavedDrive      0.177100
Electrical      0.171025
...                  ...
MoSold          0.046432
3SsnPorch       0.044584
BsmtCond        0.043476
HouseStyle      0.022876
Exterior1st     0.012815
Condition2      0.012413
Exterior2nd     0.001433
SaleCondition  -0.005446
BsmtFinSF2     -0.011378
BsmtHalfBath   -0.016844
MiscVal        -0.021190
Id             -0.021917
LowQualFinSF   -0.025606
YrSold         -0.028923
BsmtQual       -0.036224
Street         -0.041036
OverallCond    -0.077856
BldgType       -0.082411
MSSubClass     -0.084284
Condition1     -0.085438
LotConfig      -0.099073
RoofStyle      -0.127575
EnclosedPorch  -0.128578
ExterCond      -0.129700
KitchenAbvGr   -0.135907
SaleType       -0.137501
Neighborhood   -0.276955
HeatingQC      -0.406005
MSZoning             NaN
BsmtFinType2         NaN

[68 rows x 1 columns]

In [194]:
target = pd.DataFrame(data['SalePrice'])

In [195]:
target

      SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
5        143000
6        307000
7        200000
8        129900
9        118000
10       129500
11       345000
12       144000
13       279500
14       157000
15       132000
16       149000
17        90000
18       159000
19       139000
20       325300
21       139400
22       230000
23       129900
24       154000
25       256300
26       134800
27       306000
28       207500
29        68500
...         ...
1430     192140
1431     143750
1432      64500
1433     186500
1434     160000
1435     174000
1436     120500
1437     394617
1438     149700
1439     197000
1440     191000
1441     149300
1442     310000
1443     121000
1444     179600
1445     129000
1446     157900
1447     240000
1448     112000
1449      92000
1450     136000
1451     287090
1452     145000
1453      84500
1454     185000
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [196]:
featuresList = ['OverallQual','GrLivArea','GarageCars','GarageArea','TotalBsmtSF','1stFlrSF','FullBath','TotRmsAbvGrd','YearBuilt','YearRemodAdd']

In [197]:
featuresList

['OverallQual',
 'GrLivArea',
 'GarageCars',
 'GarageArea',
 'TotalBsmtSF',
 '1stFlrSF',
 'FullBath',
 'TotRmsAbvGrd',
 'YearBuilt',
 'YearRemodAdd']

In [198]:
features = pd.DataFrame()
for i in featuresList:
  features[i]=data[i]

In [199]:
features

,OverallQual,GrLivArea,GarageCars,GarageArea,TotalBsmtSF,1stFlrSF,FullBath,TotRmsAbvGrd,YearBuilt,YearRemodAdd
0,7,1710,2,548,856,856,2,8,2003,2003
1,6,1262,2,460,1262,1262,2,6,1976,1976
2,7,1786,2,608,920,920,2,6,2001,2002
3,7,1717,3,642,756,961,1,7,1915,1970
4,8,2198,3,836,1145,1145,2,9,2000,2000
5,5,1362,2,480,796,796,1,5,1993,1995
6,8,1694,2,636,1686,1694,2,7,2004,2005
7,7,2090,2,484,1107,1107,2,7,1973,1973
8,7,1774,2,468,952,1022,2,8,1931,1950
9,5,1077,1,205,991,1077,1,5,1939,1950
10,5,1040,1,384,1040,1040,1,5,1965,1965
11,9,2324,3,736,1175,1182,3,11,2005,2006
12,5,912,1,352,912,912,1,4,1962,1962
13,7,1494,3,840,1494,1494,2,7,2006,2007
14,6,1253,1,352,1253,1253,1,5,1960,1960
15,7,854,2,576,832,854,1,5,1929,2001
16,6,1004,2,480,1004,1004,1,5,1970,1970
17,4,1296,2,516,0,1296,2,6,1967,1967
18,5,1114,2,576,1114,1114,1,6,2004,2004
19,5,1339,1,294,1029,1339,1,6,1958,1965
20,8,2376,3,853,1158,1158,3,9,2005,2006
21,7,1108,1,280,637,1108,1,6,1930,1950
22,8,1795,2,534,1777,1795,2,7,2002,2002
23,5,1060,2,572,1040,1060,1,6,1976,1976
24,5,1060,1,270,1060,1060,1,6,1968,2001
25,8,1600,3,890,1566,1600,2,7,2007,2007
26,5,900,2,576,900,900,1,5,1951,2000
27,8,1704,3,772,1704,1704,2,7,2007,2008
28,5,1600,1,319,1484,1600,1,6,1957,1997
29,4,520,1,240,520,520,1,4,1927,1950
...,...,...,...,...,...,...,...,...,...,...
1430,5,1838,2,372,732,734,2,7,2005,2005
1431,6,958,2,440,958,958,2,5,1976,1976
1432,4,968,1,216,656,968,2,5,1927,2007
1433,6,1792,2,451,936,962,2,8,2000,2000
1434,5,1126,2,484,1126,1126,2,5,1977,1977
1435,6,1537,2,462,1319,1537,1,7,1962,2005
1436,4,864,2,528,864,864,1,5,1971,1971
1437,8,1932,3,774,1932,1932,2,7,2008,2008
1438,6,1236,2,923,912,1236,1,6,1957,1996
1439,7,1725,2,550,539,1040,2,6,1979,1979
1440,6,2555,2,672,588,1423,2,11,1922,1994
1441,6,848,2,420,848,848,1,3,2004,2004
1442,10,2007,3,812,1017,1026,2,10,2008,2008
1443,6,952,1,192,952,952,1,4,1916,1950
1444,7,1422,2,626,1422,1422,2,7,2004,2004
1445,6,913,1,240,814,913,1,6,1966,1966
1446,5,1188,1,312,1188,1188,1,6,1962,1962
1447,8,2090,2,556,1220,1220,2,8,1995,1996
1448,4,1346,1,384,560,796,1,6,1910,2000
1449,5,630,0,0,630,630,1,3,1970,1970
1450,5,1792,0,0,896,896,2,8,1974,1974
1451,8,1578,3,840,1573,1578,2,7,2008,2009
1452,5,1072,2,525,547,1072,1,5,2005,2005
1453,5,1140,0,0,1140,1140,1,6,2006,2006
1454,7,1221,2,400,1221,1221,2,6,2004,2005
1455,6,1647,2,460,953,953,2,7,1999,2000
1456,6,2073,2,500,1542,2073,2,7,1978,1988
1457,7,2340,1,252,1152,1188,2,9,1941,2006
1458,5,1078,1,240,1078,1078,1,5,1950,1996
1459,5,1256,1,276,1256,1256,1,6,1965,1965

In [200]:
cutoff = int(len(features)*3/4)

In [201]:
train_features = features[:cutoff]
test_features = features[cutoff:]


train_target = target[:cutoff]
test_target = target[cutoff:]